Update GA artifact v1 & v2 to v4 (#31)
* Update GA artifact v1 & 2 to v4
Github Actions upload and download artifacts v1 and 2 no longer work. Update as advised to v4.

* Make source directory explicit, and fix artifacts directories
Make distinct artifact directories with the root being the Github Actions environment variable `github.workspace`.

* Name cannot be the file path
A side effect of the previous "source" path being specified as a single word was that it passed without error as a name, but on changing the variable to a complete path GA produces an error stating:
Error: The artifact name is not valid: …  Contains the following character:  Forward slash /
… In other words, the name cannot be a file path.